# Generated by Django 3.2.16 on 2023-01-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
