# Generated by Django 3.2.16 on 2023-01-14 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_time_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
