# Generated by Django 3.2.16 on 2023-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230115_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
