# Generated by Django 3.2.16 on 2023-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_viewcount_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='country',
        ),
        migrations.AddField(
            model_name='allvisitcount',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
