# Generated by Django 3.2.16 on 2023-01-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230116_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allvisitcount',
            name='country',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
